#!/bin/bash
set -eu

upf_udp_tunnel_port="${1}"

upf_fqdn=mb-upf.open5gs.org
upf_ip=$(dig +short "${upf_fqdn}")

multicast_group_ip=239.0.0.25


request='
{
  "distSession": {
    "distSessionId": "3e3dc3fb-0677-42a3-86c6-bc44e3544b0f",
    "distSessionState": "ACTIVE",
    "mbUpfTunAddr": {
      "ipv4Addr": "'"${upf_ip}"'",
      "portNumber": '"${upf_udp_tunnel_port}"'
    },
    "upTrafficFlowInfo": {
      "destIpAddr": {
        "ipv4Addr": "'"${multicast_group_ip}"'"
      },
      "portNumber": 5000
    },
    "mbr": "10 Mbps",
    "objDistributionData": {
      "objDistributionOperatingMode": "SINGLE",
      "objAcquisitionMethod": "PUSH",
      "objDistributionBaseUrl": "http://127.0.0.2/"
    }
  }
}
'

echo "Request:"
echo "${request}"
#newline
echo

response=$(curl --silent --http2-prior-knowledge --header "Content-Type: application/json" \
    --data "${request}" \
    mbstf.5g-mag.com:7777/nmbstf-distsession/v1/dist-sessions)
echo "Response:"
echo "${response}" | jq
#newline
echo

echo "${response}" | jq -r '"URL=\(.distSession.objDistributionData.objIngestBaseUrl)"'

#newline
echo
