#!/bin/bash
set -eu

session_id="${1}"

upf_fqdn=mb-upf.open5gs.org
upf_ip=$(dig +short "${upf_fqdn}")

mediaserver_fqdn=mediaserver.5g-mag.com
mediaserver_ip=$(dig +short "${mediaserver_fqdn}")

multicast_group_ip=239.0.0.25

request='[{"op":"replace", "path":"/distSession/distSessionState", "value":"ACTIVE"}]'

echo "Request:"
echo "${request}" | jq

echo "Response:"
curl --silent -X PATCH --http2-prior-knowledge --header "Content-Type: application/json-patch+json" \
    --data "${request}" \
    mbstf.5g-mag.com:7777/nmbstf-distsession/v1/dist-sessions/"${session_id}" | jq

#newline
echo
