#!/bin/bash
set -eu

mbstf_fqdn=mbstf.5g-mag.com
mbstf_ip=$(dig +short "${mbstf_fqdn}")

multicast_group_ip=239.0.0.25

request='{ "mbsSession": { "mbsSessionId": { "ssm": { "sourceIpAddr": { "ipv4Addr": "'"${mbstf_ip}"'" }, "destIpAddr": { "ipv4Addr": "'"${multicast_group_ip}"'" } } }, "tmgiAllocReq": true, "serviceType": "MULTICAST", "ingressTunAddrReq": true, "activityStatus": "ACTIVE", "anyUeInd": true } }'

echo "Request:"
echo "${request}"

response=$(curl --silent --http2-prior-knowledge --header "Content-Type: application/json" \
    --data "${request}" \
    mb-smf.open5gs.org:80/nmbsmf-mbssession/v1/mbs-sessions)

echo "Response:"
echo "${response}" | jq
#newline
echo

echo "${response}" | jq -r '"UDP_TUNNEL_PORT=\(.mbsSession.ingressTunAddr[0].portNumber)"'

#newline
echo
