[rf]
freq_offset = 0
tx_gain = 50
rx_gain = 40
srate = 23.04e6
nof_antennas = 1

device_name = zmq
device_args = tx_port=tcp://${UE2_IP}:2201,rx_port=tcp://${GNURADIO_IP}:2200,base_srate=23.04e6

[rat.eutra]
dl_earfcn = 2850
nof_carriers = 0

[rat.nr]
bands = 3
nof_carriers = 1
max_nof_prb = 106
nof_prb = 106

[pcap]
enable = none
mac_filename = /tmp/mb-ue_mac.pcap
mac_nr_filename = /tmp/mb-ue_mac_nr.pcap
nas_filename = /tmp/mb-ue_nas.pcap

[log]
all_level = none
all_hex_limit = 32
filename = stdout
file_max_size = -1

rlc_level = info
pdcp_level = info

[usim]
mode = soft
algo = milenage
opc  = 00000000000000000000000000000000
k    = 00000000000000000000000000000000
imsi = 001011234567891
imei = 353490069873319

[rrc]
release = 15
ue_category = 4

[slicing]
enable = false
nssai-sst = 1
nssai-sd = 1

[nas]
apn = internet
apn_protocol = ipv4

[gw]
ip_devname = tun_srsue
ip_netmask = 255.255.255.0

[gui]
enable = false

[phy]
nof_phy_threads = 1
