#!/bin/bash
set -x
smcroutectl reload
sleep 0.1 
smcroutectl join tun_srsue 239.0.0.25
sleep 0.1 
#mpv --quiet --vo=caca --profile=low-latency --no-cache --untimed --video-sync=audio --demuxer-lavf-o-add=fflags=+nobuffer "udp://239.0.0.25:9988"
#mpv --profile=low-latency --cache=yes --demuxer-max-bytes=1MiB --demuxer-readahead-secs=0.1 --quiet --vo=caca "udp://239.0.0.25:9988"
mpv --quiet --vo=caca --profile=low-latency "udp://239.0.0.25:9988"
